meta:
  url: https://quramy.github.io/ts-server-side-anatomy/
  name: TypeScript Server Side Anatomy
  author: Quramy
  thumbnail: https://quramy.github.io/ts-server-side-anatomy/assets/ogp.png
  description: Explain what TypeScript server(tsserver) does under your editors
  sns:
    - twitter
slide:
  loop: false
  sidebar: true
  targetBlank: true
  showIndex: false
  isVertical: false
  code:
    languages:
      - bash
      - javascript
      - typescript
    plugins: []
    theme: default
extends:
  js: index.js
  css: styles.css
