meta:
  url:
  name:
  author:
  thumbnail:
  description:
  sns:
    - twitter
slide:
  loop: false
  sidebar: true
  targetBlank: true
  showIndex: false
  isVertical: false
  code:
    languages:
      - bash
      - javascript
      - typescript
    plugins: []
    theme: default
extends:
  js: index.js
  css: styles.css
